version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CONFLUENCE_URL=your_confluence_url
      - CONFLUENCE_PAT=your_personal_access_token
      - OPENAI_API_KEY=your_openai_key
      - ANTHROPIC_API_KEY=your_anthropic_key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ragbot
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: